/* ------------------------------------------------------------------ */
/* Object book (도감) & discoveries: what every prop is good for and    */
/* the special interactions a curious cat can find out by playing.      */
/* ------------------------------------------------------------------ */

export interface ObjInfo { icon: string; tip: string }

export const OBJECTS: Record<string, ObjInfo> = {
  mug: { icon: '☕', tip: '가볍고 잘 깨져요. 던지듯 세게 치면 멀리 날아가요.' },
  vase: { icon: '🏺', tip: '비싸고 약해요. 높은 곳에서 떨어뜨리면 확실히 와장창.' },
  plate: { icon: '🍽️', tip: '포개진 접시는 한 번에 와르르. 식탁보와 함께라면 더 좋아요.' },
  teapot: { icon: '🫖', tip: '도자기라 잘 깨져요. 찻잔 세트 옆에 두면 연쇄의 시작.' },
  piggy: { icon: '🐷', tip: '깨지면 동전이 쏟아져 주변 물건을 건드려요.' },
  plant: { icon: '🪴', tip: '흙이 쏟아지면 얼룩이 남아요. 무거워서 아래 물건을 눌러 깨요.' },
  glass: { icon: '🍷', tip: '아주 약해요. 살짝 넘어지기만 해도 쨍그랑.' },
  cup: { icon: '🥤', tip: '쏟아지면 바닥이 끈적끈적.' },
  bottle: { icon: '🍾', tip: '길쭉해서 잘 넘어지고, 넘어지면 굴러가요.' },
  marbleJar: { icon: '🫙', tip: '깨지면 구슬이 사방으로 굴러가 다른 물건을 넘어뜨려요.' },
  marble: { icon: '🔵', tip: '작지만 빠르게 굴러가요.' },
  book: { icon: '📕', tip: '줄 세운 책은 도미노가 돼요. 쌓인 책은 계단이 되기도.' },
  domino: { icon: '🁢', tip: '첫 조각만 살짝! 마지막 조각 끝에 무엇이 있는지 보세요.' },
  ball: { icon: '⚽', tip: '통통 튀고 멀리 굴러가요. 멀리 있는 물건을 맞히기 좋아요.' },
  yarn: { icon: '🧶', tip: '굴러가는 길을 따라 실이 풀려요.' },
  duck: { icon: '🐤', tip: '삑! 소리가 나요. 자는 집사가 싫어하는 소리.' },
  car: { icon: '🚗', tip: '바퀴가 있어 쭉 미끄러져 가요.' },
  roomba: { icon: '🤖', tip: '치면 그 방향으로 달려가 부딪히는 것마다 방향을 틀어요.' },
  soda: { icon: '🥤', tip: '흔들린 탄산음료는 로켓처럼 날아가요. 높은 선반을 노려요!' },
  cushion: { icon: '🛋️', tip: '푹신해서 떨어지는 물건을 받아내요. 치우거나 활용하거나.' },
  tv: { icon: '📺', tip: '무거워서 앞발로는 꿈쩍 안 해요. 위에서 무언가 떨어지면…?' },
  laptop: { icon: '💻', tip: '바닥에 떨어지면 끝. 앞을 막은 물건을 먼저 치워요.' },
  lamp: { icon: '💡', tip: '키가 커서 쓰러지면 멀리 있는 물건까지 닿아요.' },
  deskLamp: { icon: '🔦', tip: '책상 위를 쓸어버리는 빗자루가 돼요.' },
  alarm: { icon: '⏰', tip: '떨어지거나 부딪히면 울려요. 잠든 집사 곁이라면 효과 만점.' },
  egg: { icon: '🥚', tip: '가장 약한 물건. 살짝 굴러 떨어져도 퍽!' },
  carton: { icon: '🥚', tip: '통째로 떨어뜨리면 달걀이 한꺼번에.' },
  flour: { icon: '🌾', tip: '터지면 부엌이 하얗게 변해요.' },
  pot: { icon: '🍲', tip: '무겁고 단단해요. 떨어지면 아래 물건을 박살 내요.' },
  pin: { icon: '🥖', tip: '굴리면 일렬로 선 물건을 한 번에 쓸어요.' },
  fruit: { icon: '🍎', tip: '굴러가다 다른 물건을 톡 건드려요.' },
  cake: { icon: '🎂', tip: '철퍽! 크림이 사방에 튀어요.' },
  toaster: { icon: '🍞', tip: '레버를 치면 잠시 뒤 빵이 튀어 올라요. 선반 아래에 두면…?' },
  toast: { icon: '🍞', tip: '토스터가 쏘아 올린 빵.' },
  cloth: { icon: '🧺', tip: '살살 당기면 전부 끌려 떨어지고, 확 잡아빼면 마술이 돼요.' },
  bookshelf: { icon: '📚', tip: '높은 곳을 칠수록 크게 흔들려요. 흔들릴 때 한 번 더!' },
  sidetable: { icon: '🪑', tip: '다리가 가늘어 잘 넘어가요.' },
  chair: { icon: '🪑', tip: '바퀴 달린 의자는 쭉 밀려가 부딪혀요.' },
  frame: { icon: '🖼️', tip: '벽에 걸린 액자는 충격을 받으면 떨어져요.' },
  shelf: { icon: '🪵', tip: '벽 선반은 아래에서 세게 부딪히면 통째로 떨어져요.' },
  trophy: { icon: '🏆', tip: '무거운 금속. 아래 있는 물건에겐 재앙.' },
  globe: { icon: '🌍', tip: '공처럼 굴러가요.' },
  pencup: { icon: '✏️', tip: '쏟아지면 연필이 우수수.' },
  papers: { icon: '📄', tip: '서류가 흩날려요. 집사의 마감이 위험해요.' },
  seesaw: { icon: '🪃', tip: '한쪽에 무거운 게 떨어지면 반대쪽이 날아올라요.' },
  soap: { icon: '🧼', tip: '마찰이 거의 없어요. 툭 치면 방 끝까지 미끄러져요.' },
  tp: { icon: '🧻', tip: '굴러가는 만큼 휴지가 풀려요. 길게 풀수록 기록!' },
  phone: { icon: '📱', tip: '물에 빠지면 고장. 욕조나 변기를 노려요.' },
  perfume: { icon: '🌸', tip: '깨지면 향기 구름이 퍼져요. 냄새에 집사가 뒤척여요.' },
  shampoo: { icon: '🧴', tip: '통통 튀고 물에 떠요.' },
  toothcup: { icon: '🪥', tip: '얇은 유리컵. 살짝만 떨어져도 깨져요.' },
  dryer: { icon: '💨', tip: '치면 켜져서 바람으로 가벼운 물건을 날려요.' },
  block: { icon: '🧱', tip: '블록 성은 아래 기둥을 치면 와르르. 위에 있는 걸 노려요.' },
  doll: { icon: '🎎', tip: '비싼 도자기 인형. 블록 성 꼭대기를 좋아해요.' },
  globeSnow: { icon: '🔮', tip: '깨지면 실내에 눈보라가 일어요.' },
  balloon: { icon: '🎈', tip: '세게 부딪히면 펑! 매달려 있던 물건이 떨어져요.' },
  jack: { icon: '🎁', tip: '치면 광대가 튀어나와 위에 있는 물건을 쏘아 올려요.' },
  train: { icon: '🚂', tip: '치면 레일을 따라 달려 길 위의 물건을 들이받아요.' },
  plush: { icon: '🧸', tip: '푹신해서 물건을 받아내요. 물에 뜨기도.' },
  coatRack: { icon: '🧥', tip: '키가 크고 위가 무거워 쓰러지면 멀리까지 닿아요.' },
  umbrella: { icon: '☂️', tip: '쓰러지면 우산이 굴러가요.' },
  grandClock: { icon: '🕰️', tip: '아주 무겁고 비싸요. 쓰러뜨리면 집 전체가 울려요.' },
  aquarium: { icon: '🐟', tip: '깨지면 물난리! 바닥이 물바다가 돼요.' },
  fan: { icon: '🌀', tip: '치면 켜져서 앞쪽으로 강한 바람을 불어요.' },
  shoe: { icon: '👟', tip: '가볍게 날아가 다른 물건을 톡.' },
  pillow: { icon: '☁️', tip: '아주 세게 맞으면 깃털이 폭발해요.' },
  guitar: { icon: '🎸', tip: '넘어지면 줄이 끊어져요. 띠로링~' },
  cereal: { icon: '🥣', tip: '쏟아지면 시리얼 비가 내려요.' },
  milk: { icon: '🥛', tip: '쏟아지면 하얀 웅덩이.' },
  pan: { icon: '🍳', tip: '단단한 금속. 시소처럼 쓸 수도 있어요.' },
  gadget: { icon: '🔊', tip: '작은 전자제품. 물에 빠지면 지지직, 끝장이에요.' },
  stool: { icon: '🪑', tip: '젖은 의자는 미끄러워요. 무언가 부딪히면 쭉 밀려가요.' },
  basket: { icon: '🧺', tip: '빨래가 가득. 넘어지면 와르르 쏟아져요.' },
  towel: { icon: '🧺', tip: '폭신해서 떨어지는 물건을 조용히 받아내요.' },
  slipper: { icon: '🩴', tip: '가볍게 날아가 다른 물건을 톡 건드려요.' },
  // ---- the outside world
  auto: { icon: '🚗', tip: '앞발로는 흠집뿐. 경사 위에서 고임목을 빼면…?' },
  chock: { icon: '🔺', tip: '바퀴를 붙잡는 쐐기. 빼면 차가 굴러가요.' },
  gate: { icon: '🚪', tip: '툭 치면 열려요. 길을 열지 막을지 골라요.' },
  gnome: { icon: '🧙', tip: '정원 난쟁이. 작고 잘 깨져요.' },
  mailbox: { icon: '📮', tip: '기둥이 가늘어 잘 넘어가요.' },
  birdbath: { icon: '⛲', tip: '깨지면 물이 쏟아져 바닥이 미끄러워요.' },
  flowerPot: { icon: '🪴', tip: '토분은 잘 깨지고, 줄지어 있으면 연달아 넘어가요.' },
  bin: { icon: '🗑️', tip: '바퀴 달린 쓰레기통. 쭉 밀려가 부딪혀요.' },
  bonsai: { icon: '🌳', tip: '수십 년 가꾼 분재. 높은 받침대 위에 있어요.' },
  hose: { icon: '🚿', tip: '치면 물줄기가 나와 가벼운 걸 밀고 바닥을 적셔요.' },
  wateringCan: { icon: '🪣', tip: '쏟아지면 웅덩이가 생겨요.' },
  parcel: { icon: '📦', tip: '"깨지기 쉬움" 상자. 높이 쌓여 있어요.' },
  handTruck: { icon: '🛒', tip: '바퀴 달린 운반 수레. 위에 실린 걸 함께 싣고 가요.' },
  lever: { icon: '🕹️', tip: '툭 치면 큰 장치가 움직여요.' },
  onggi: { icon: '🏺', tip: '무거운 장독. 앞발로는 꿈쩍, 떨어지면 간장이 콸콸.' },
  cart: { icon: '🛒', tip: '바퀴 달린 수레. 실린 짐은 수레가 멈출 때 앞으로 날아가요.' },
  brick: { icon: '🧱', tip: '무겁고 단단해요. 수레에 실려 날아가면 무기가 돼요.' },
  lantern: { icon: '🏮', tip: '돌로 된 석등. 넘어지면 아래 것을 부숴요.' },
  bucket: { icon: '🪣', tip: '엎어지면 물이 쏟아져 미끄러워요.' },
  strip: { icon: '🔌', tip: '멀티탭. 물이 닿으면 꽂힌 전자제품이 전부 고장.' },
  waterBottle: { icon: '💧', tip: '정수기 물통. 터지면 사무실이 물바다.' },
  monitor: { icon: '🖥️', tip: '새 모니터. 전선으로 옆 모니터와 이어져 있어요.' },
  desk: { icon: '🗄️', tip: '무거운 책상. 세게 부딪히면 위의 물건이 흔들려요.' },
  cooler: { icon: '🚰', tip: '물통이 떨어지면 사무실이 물바다. 젖은 전자제품은 고장.' },
  printer: { icon: '🖨️', tip: '무겁고 비싸요. 떨어지면 종이가 흩날려요.' },
  vitrine: { icon: '🗄️', tip: '무거운 유리장. 흔들릴 때 한 번 더 치면 넘어가요.' },
  moonJar: { icon: '🏺', tip: '장인의 달항아리. 유리장 안에 있어 직접은 못 쳐요.' },
  rack: { icon: '🛒', tip: '바퀴 달린 건조대. 굴러가 부딪히면 무거운 것도 흔들려요.' },
  greenware: { icon: '🏺', tip: '굽기 전의 그릇. 아주 약해요.' },
  maebyeong: { icon: '🏺', tip: '가늘고 키 큰 매병. 줄지어 서 있으면 도미노.' },
  clay: { icon: '🟫', tip: '무거운 점토. 실려 가다 멈추면 앞으로 날아가요.' },
  fragile: { icon: '📦', tip: '"깨지기 쉬움". 떨어지거나 세게 맞으면 안에서 쨍그랑.' },
  watermelon: { icon: '🍉', tip: '굴러가는 수박. 경사로에서 속도가 붙어요.' },
  vending: { icon: '🥤', tip: '무겁고 비싼 자판기. 차 정도는 와야 넘어가요.' },
  window: { icon: '🪟', tip: '큰 유리창. 무거운 것이 부딪히면 와장창.' },
  trafficCone: { icon: '🚧', tip: '가볍게 넘어지고 굴러가요.' },
  crate: { icon: '🍊', tip: '깨지면 과일이 데굴데굴 굴러 나와요.' },
  waterPack: { icon: '💧', tip: '무거운 생수 묶음.' },
  button: { icon: '🔴', tip: '누르면 무언가 시작돼요.' },
};

export interface Discovery { id: string; icon: string; name: string; desc: string }

/** special interactions found by playing (each pays out once) */
export const DISCOVERIES: Discovery[] = [
  { id: 'heavy', icon: '🐘', name: '꿈쩍도 안 해', desc: '무거운 물건은 앞발로는 안 밀려요. 위에서 떨어뜨리거나 다른 물건으로 쳐요.' },
  { id: 'domino', icon: '🁢', name: '도미노 효과', desc: '줄지어 선 물건은 하나만 밀어도 연달아 쓰러져요.' },
  { id: 'furniture', icon: '🛋️', name: '가구 넘기기', desc: '무거운 가구도 높은 곳을 연달아 치면 넘어가요.' },
  { id: 'shelf', icon: '🪵', name: '선반 붕괴', desc: '벽에 고정된 물건도 세게 부딪히면 통째로 떨어져요.' },
  { id: 'rocket', icon: '🚀', name: '탄산 로켓', desc: '흔들린 탄산음료는 로켓처럼 날아가요.' },
  { id: 'toast', icon: '🍞', name: '토스트 발사', desc: '토스터 레버를 치면 잠시 뒤 빵이 튀어 올라요.' },
  { id: 'magic', icon: '🎩', name: '식탁보 마술', desc: '식탁보를 확 잡아빼면 그릇은 제자리에 남아요.' },
  { id: 'clothPull', icon: '🧺', name: '식탁 대청소', desc: '식탁보를 살살 당기면 위의 물건이 전부 끌려 떨어져요.' },
  { id: 'alarm', icon: '⏰', name: '모닝콜', desc: '자명종은 떨어지거나 부딪히면 울려요.' },
  { id: 'wake', icon: '😫', name: '집사 기상', desc: '소음과 충격이 쌓이면 집사가 깨요.' },
  { id: 'bonk', icon: '💫', name: '머리 위 낙하', desc: '자는 집사 머리에 물건이 떨어지면 크게 놀라요.' },
  { id: 'roomba', icon: '🤖', name: '로봇청소기 폭주', desc: '로봇청소기를 치면 그 방향으로 달려가 이것저것 들이받아요.' },
  { id: 'marbles', icon: '🔮', name: '구슬 대방출', desc: '구슬병이 깨지면 구슬이 사방으로 굴러가요.' },
  { id: 'flour', icon: '☁️', name: '밀가루 폭탄', desc: '밀가루 봉지가 터지면 부엌이 하얗게.' },
  { id: 'piggy', icon: '🪙', name: '저금통 털기', desc: '돼지저금통을 깨면 동전이 쏟아져요.' },
  { id: 'zap', icon: '⚡', name: '파지직', desc: '전자제품은 충격과 물에 약해요.' },
  { id: 'splash', icon: '💦', name: '풍덩!', desc: '물에 빠진 물건: 가벼운 건 둥둥, 전자제품은 고장.' },
  { id: 'soap', icon: '🧼', name: '미끄러운 비누', desc: '비누는 바닥을 끝없이 미끄러져요.' },
  { id: 'tp', icon: '🧻', name: '휴지 풀기', desc: '두루마리 휴지를 굴리면 길게 풀려요.' },
  { id: 'yarn', icon: '🧶', name: '털실 아트', desc: '털실뭉치가 굴러가며 실을 남겨요.' },
  { id: 'fan', icon: '🌀', name: '바람의 힘', desc: '선풍기나 드라이기를 켜면 가벼운 물건이 날아가요.' },
  { id: 'balloon', icon: '🎈', name: '풍선 펑!', desc: '풍선이 터지면 매달려 있던 물건이 떨어져요.' },
  { id: 'jack', icon: '🎁', name: '깜짝 상자', desc: '광대가 튀어나와 위에 있던 물건을 쏘아 올려요.' },
  { id: 'train', icon: '🚂', name: '폭주 기관차', desc: '기차는 레일을 따라 달려 길 위의 물건을 들이받아요.' },
  { id: 'flood', icon: '🌊', name: '물난리', desc: '수조가 깨지면 바닥이 물바다.' },
  { id: 'perfume', icon: '🌸', name: '향기 폭탄', desc: '향수병이 깨지면 향기 구름이 퍼져요.' },
  { id: 'snow', icon: '❄️', name: '실내 눈보라', desc: '스노우볼이 깨지면 눈이 흩날려요.' },
  { id: 'feathers', icon: '🪶', name: '깃털 폭발', desc: '베개가 터지면 깃털이 흩날려요.' },
  { id: 'breakfast', icon: '🥣', name: '아침밥 대참사', desc: '시리얼과 우유가 바닥에 쏟아졌어요.' },
  { id: 'castle', icon: '🏰', name: '성 무너뜨리기', desc: '블록 성은 아래 기둥을 치면 와르르 무너져요.' },
  { id: 'slick', icon: '🫧', name: '미끄덩 웅덩이', desc: '쏟아진 물·우유·페인트 위에서는 물건이 쭉 미끄러져요.' },
  // ---- the outside world
  { id: 'chock', icon: '🔺', name: '고임목 빼기', desc: '경사 위의 차는 고임목만 빼면 스스로 굴러가요.' },
  { id: 'carAlarm', icon: '🚨', name: '삐용삐용', desc: '차가 찌그러지면 경보가 울려요.' },
  { id: 'carWreck', icon: '💥', name: '전손 처리', desc: '차가 크게 부딪히면 완전히 망가져요.' },
  { id: 'trigger', icon: '🕹️', name: '방아쇠', desc: '레버·버튼 하나가 큰 장치를 움직여요.' },
  { id: 'hose', icon: '🚿', name: '물줄기', desc: '호스를 틀면 가벼운 것이 밀려나고 바닥이 젖어요.' },
  { id: 'gate', icon: '🚪', name: '길 열기', desc: '문과 차단기를 열면 굴러가는 것의 길이 바뀌어요.' },
  { id: 'cable', icon: '🔌', name: '줄줄이 케이블', desc: '전선으로 이어진 물건은 하나가 떨어지면 옆 것도 끌려가요.' },
  { id: 'carry', icon: '🛒', name: '실어 보내기', desc: '바퀴 달린 것 위에 실린 물건은 함께 실려 가요.' },
  { id: 'hairball', icon: '🌀', name: '헤어볼', desc: '헤어볼 웅덩이 위에서는 무엇이든 미끄러져요.' },
  { id: 'knead', icon: '🍑', name: '꾹꾹이', desc: '고양이 무게로 시소·레버·저울을 눌러요.' },
  { id: 'caught', icon: '👀', name: '현행범', desc: '사람이 보는 앞에서 사고를 치면 들켜요.' },
  { id: 'perfect', icon: '😇', name: '완전 범죄', desc: '아무도 못 봤어요. 장난 점수가 1.3배.' },
];

export const discoveryById = (id: string) => DISCOVERIES.find((d) => d.id === id);

/** break-fx → discovery id */
export const FX_DISCOVERY: Record<string, string> = {
  flour: 'flour', coins: 'piggy', sparks: 'zap', feathers: 'feathers', perfume: 'perfume', snow: 'snow', cereal: 'breakfast', milk: 'breakfast',
};
